; Generated by AC Compiler v1.0.0 — target: x86_64-linux-gnu
; Assemble: nasm -felf64 output.asm
; Link:     gcc output.o runtime.o -o program

section .text


global fib_recursive
fib_recursive:
    push rbp
    mov rbp, rsp
    sub rsp, 112
    mov qword [rbp-8], rdi
    ; [inst]
    lea rax, [rbp-16]
    mov qword [rbp-16], rax
    ; [mov]
    mov rax, 0
    mov qword [rbp-8], rax
    ; [inst]
    mov rax, qword [rbp-16]
    mov rcx, qword [rbp-8]
    mov qword [rax], rcx
    ; [inst]
    mov rax, qword [rbp-16]
    mov rax, qword [rax]
    mov qword [rbp-24], rax
    ; [inst]
    mov rax, qword [rbp-24]
    mov rcx, 1
    cmp rax, rcx
    setbe al
    movzx rax, al
    mov qword [rbp-32], rax
    ; [inst]
    mov rax, qword [rbp-32]
    test rax, rax
    jnz .L1
    jmp .L2
    ; [inst]
.L1:
.L1:
    ; [inst]
    mov rax, qword [rbp-16]
    mov rax, qword [rax]
    mov qword [rbp-40], rax
    ; [ret]
    mov rax, qword [rbp-40]
    leave
    ret
.L2:
    ; [inst]
    mov rax, qword [rbp-16]
    mov rax, qword [rax]
    mov qword [rbp-48], rax
    ; [inst]
    mov rax, qword [rbp-48]
    mov rcx, 1
    sub rax, rcx
    mov qword [rbp-56], rax
    ; [call]
    mov rdi, qword [rbp-56]
    xor eax, eax
    call fib_recursive
    mov qword [rbp-64], rax
    ; [inst]
    mov rax, qword [rbp-16]
    mov rax, qword [rax]
    mov qword [rbp-72], rax
    ; [inst]
    mov rax, qword [rbp-72]
    mov rcx, 2
    sub rax, rcx
    mov qword [rbp-80], rax
    ; [call]
    mov rdi, qword [rbp-80]
    xor eax, eax
    call fib_recursive
    mov qword [rbp-88], rax
    ; [add]
    mov rax, qword [rbp-64]
    mov rcx, qword [rbp-88]
    add rax, rcx
    mov qword [rbp-96], rax
    ; [ret]
    mov rax, qword [rbp-96]
    leave
    ret
.L3:
    ; [inst]
.L2:
.L4:
    ; [ret]
    leave
    ret
    ; implicit void return
    leave
    ret


global fib_iterative
fib_iterative:
    push rbp
    mov rbp, rsp
    sub rsp, 208
    mov qword [rbp-8], rdi
    ; [inst]
    lea rax, [rbp-16]
    mov qword [rbp-16], rax
    ; [mov]
    mov rax, 0
    mov qword [rbp-8], rax
    ; [inst]
    mov rax, qword [rbp-16]
    mov rcx, qword [rbp-8]
    mov qword [rax], rcx
    ; [inst]
    mov rax, qword [rbp-16]
    mov rax, qword [rax]
    mov qword [rbp-24], rax
    ; [inst]
    mov rax, qword [rbp-24]
    mov rcx, 1
    cmp rax, rcx
    setbe al
    movzx rax, al
    mov qword [rbp-32], rax
    ; [inst]
    mov rax, qword [rbp-32]
    test rax, rax
    jnz .L1
    jmp .L2
    ; [inst]
.L1:
.L1:
    ; [inst]
    mov rax, qword [rbp-16]
    mov rax, qword [rax]
    mov qword [rbp-40], rax
    ; [ret]
    mov rax, qword [rbp-40]
    leave
    ret
.L2:
    ; [inst]
    lea rax, [rbp-48]
    mov qword [rbp-48], rax
    ; [inst]
    mov rax, qword [rbp-48]
    mov rcx, 0
    mov qword [rax], rcx
    ; [inst]
    lea rax, [rbp-56]
    mov qword [rbp-56], rax
    ; [inst]
    mov rax, qword [rbp-56]
    mov rcx, 1
    mov qword [rax], rcx
    ; [inst]
    lea rax, [rbp-64]
    mov qword [rbp-64], rax
    ; [inst]
    mov rax, qword [rbp-64]
    mov rcx, 2
    mov qword [rax], rcx
    ; [inst]
    jmp .L4
    ; [inst]
.L4:
.L3:
    ; [inst]
.L2:
.L4:
    ; [inst]
    mov rax, qword [rbp-64]
    mov rax, qword [rax]
    mov qword [rbp-72], rax
    ; [inst]
    mov rax, qword [rbp-16]
    mov rax, qword [rax]
    mov qword [rbp-80], rax
    ; [inst]
    mov rax, qword [rbp-72]
    mov rcx, qword [rbp-80]
    cmp rax, rcx
    setbe al
    movzx rax, al
    mov qword [rbp-88], rax
    ; [inst]
    mov rax, qword [rbp-88]
    test rax, rax
    jnz .L5
    jmp .L6
    ; [inst]
.L5:
.L5:
    ; [inst]
    lea rax, [rbp-96]
    mov qword [rbp-96], rax
    ; [inst]
    mov rax, qword [rbp-48]
    mov rax, qword [rax]
    mov qword [rbp-104], rax
    ; [inst]
    mov rax, qword [rbp-56]
    mov rax, qword [rax]
    mov qword [rbp-112], rax
    ; [add]
    mov rax, qword [rbp-104]
    mov rcx, qword [rbp-112]
    add rax, rcx
    mov qword [rbp-120], rax
    ; [inst]
    mov rax, qword [rbp-96]
    mov rcx, qword [rbp-120]
    mov qword [rax], rcx
    ; [inst]
    mov rax, qword [rbp-56]
    mov rax, qword [rax]
    mov qword [rbp-128], rax
    ; [inst]
    mov rax, qword [rbp-48]
    mov rcx, qword [rbp-128]
    mov qword [rax], rcx
    ; [inst]
    mov rax, qword [rbp-96]
    mov rax, qword [rax]
    mov qword [rbp-136], rax
    ; [inst]
    mov rax, qword [rbp-56]
    mov rcx, qword [rbp-136]
    mov qword [rax], rcx
    ; [inst]
    mov rax, qword [rbp-64]
    mov rax, qword [rax]
    mov qword [rbp-144], rax
    ; [add]
    mov rax, qword [rbp-144]
    mov rcx, 1
    add rax, rcx
    mov qword [rbp-152], rax
    ; [inst]
    mov rax, qword [rbp-64]
    mov rcx, qword [rbp-152]
    mov qword [rax], rcx
    ; [inst]
    jmp .L4
    ; [inst]
.L6:
.L6:
    ; [inst]
    mov rax, qword [rbp-56]
    mov rax, qword [rax]
    mov qword [rbp-160], rax
    ; [ret]
    mov rax, qword [rbp-160]
    leave
    ret
.L7:
    ; [ret]
    leave
    ret
    ; implicit void return
    leave
    ret


global main
main:
    push rbp
    mov rbp, rsp
    sub rsp, 192
    ; [call]
    lea rdi, [rel .Lstr_0x608cef9155e0]
    xor eax, eax
    call printf
    mov qword [rbp-8], rax
    ; [inst]
    lea rax, [rbp-16]
    mov qword [rbp-16], rax
    ; [inst]
    mov rax, qword [rbp-16]
    mov rcx, 0
    mov qword [rax], rcx
    ; [inst]
    jmp .L1
    ; [inst]
.L1:
.L1:
    ; [inst]
    mov rax, qword [rbp-16]
    movsxd rax, dword [rax]
    mov qword [rbp-24], rax
    ; [inst]
    movsxd rax, dword [rbp-24]
    mov ecx, 15
    cmp rax, rcx
    setb al
    movzx rax, al
    mov qword [rbp-32], rax
    ; [inst]
    mov rax, qword [rbp-32]
    test rax, rax
    jnz .L2
    jmp .L3
    ; [inst]
.L2:
.L2:
    ; [inst]
    mov rax, qword [rbp-16]
    movsxd rax, dword [rax]
    mov qword [rbp-40], rax
    ; [inst]
    mov rax, qword [rbp-16]
    movsxd rax, dword [rax]
    mov qword [rbp-48], rax
    ; [inst]
    movsxd rax, dword [rbp-48]
    mov qword [rbp-56], rax
    ; [call]
    mov rdi, qword [rbp-56]
    xor eax, eax
    call fib_recursive
    mov qword [rbp-64], rax
    ; [call]
    lea rdi, [rel .Lstr_0x608cef915938]
    mov rsi, qword [rbp-40]
    mov rdx, qword [rbp-64]
    xor eax, eax
    call printf
    mov qword [rbp-72], rax
    ; [inst]
    mov rax, qword [rbp-16]
    movsxd rax, dword [rax]
    mov qword [rbp-80], rax
    ; [add]
    movsxd rax, dword [rbp-80]
    mov ecx, 1
    add rax, rcx
    mov dword [rbp-88], rax
    ; [inst]
    mov rax, qword [rbp-16]
    mov rcx, qword [rbp-88]
    mov dword [rax], ecx
    ; [inst]
    jmp .L1
    ; [inst]
.L3:
.L3:
    ; [call]
    lea rdi, [rel .Lstr_0x608cef915f08]
    xor eax, eax
    call printf
    mov qword [rbp-96], rax
    ; [inst]
    lea rax, [rbp-104]
    mov qword [rbp-104], rax
    ; [inst]
    mov rax, qword [rbp-104]
    mov rcx, 0
    mov qword [rax], rcx
    ; [inst]
    jmp .L4
    ; [inst]
.L4:
.L4:
    ; [inst]
    mov rax, qword [rbp-104]
    movsxd rax, dword [rax]
    mov qword [rbp-112], rax
    ; [inst]
    movsxd rax, dword [rbp-112]
    mov ecx, 20
    cmp rax, rcx
    setb al
    movzx rax, al
    mov qword [rbp-120], rax
    ; [inst]
    mov rax, qword [rbp-120]
    test rax, rax
    jnz .L5
    jmp .L6
    ; [inst]
.L5:
.L5:
    ; [inst]
    mov rax, qword [rbp-104]
    movsxd rax, dword [rax]
    mov qword [rbp-128], rax
    ; [inst]
    mov rax, qword [rbp-104]
    movsxd rax, dword [rax]
    mov qword [rbp-136], rax
    ; [inst]
    movsxd rax, dword [rbp-136]
    mov qword [rbp-144], rax
    ; [call]
    mov rdi, qword [rbp-144]
    xor eax, eax
    call fib_iterative
    mov qword [rbp-152], rax
    ; [call]
    lea rdi, [rel .Lstr_0x608cef917738]
    mov rsi, qword [rbp-128]
    mov rdx, qword [rbp-152]
    xor eax, eax
    call printf
    mov qword [rbp-160], rax
    ; [inst]
    mov rax, qword [rbp-104]
    movsxd rax, dword [rax]
    mov qword [rbp-168], rax
    ; [add]
    movsxd rax, dword [rbp-168]
    mov ecx, 1
    add rax, rcx
    mov dword [rbp-176], rax
    ; [inst]
    mov rax, qword [rbp-104]
    mov rcx, qword [rbp-176]
    mov dword [rax], ecx
    ; [inst]
    jmp .L4
    ; [inst]
.L6:
.L6:
    ; [ret]
    mov rax, 0
    leave
    ret
.L7:
    ; [ret]
    leave
    ret
    ; implicit void return
    leave
    ret


section .data

.Lstr_0x608cef9155e0:
    db 70, 105, 98, 111, 110, 97, 99, 99, 105, 32, 115, 101, 113, 117, 101, 110, 99, 101, 32, 40, 114, 101, 99, 117, 114, 115, 105, 118, 101, 41, 58, 92, 110, 0
.Lstr_0x608cef915938:
    db 32, 32, 102, 105, 98, 40, 37, 100, 41, 32, 61, 32, 37, 108, 108, 100, 92, 110, 0
.Lstr_0x608cef915f08:
    db 92, 110, 70, 105, 98, 111, 110, 97, 99, 99, 105, 32, 115, 101, 113, 117, 101, 110, 99, 101, 32, 40, 105, 116, 101, 114, 97, 116, 105, 118, 101, 41, 58, 92, 110, 0
.Lstr_0x608cef9155e0:
    db 70, 105, 98, 111, 110, 97, 99, 99, 105, 32, 115, 101, 113, 117, 101, 110, 99, 101, 32, 40, 114, 101, 99, 117, 114, 115, 105, 118, 101, 41, 58, 92, 110, 0
.Lstr_0x608cef915938:
    db 32, 32, 102, 105, 98, 40, 37, 100, 41, 32, 61, 32, 37, 108, 108, 100, 92, 110, 0
.Lstr_0x608cef915f08:
    db 92, 110, 70, 105, 98, 111, 110, 97, 99, 99, 105, 32, 115, 101, 113, 117, 101, 110, 99, 101, 32, 40, 105, 116, 101, 114, 97, 116, 105, 118, 101, 41, 58, 92, 110, 0
.Lstr_0x608cef916260:
    db 32, 32, 102, 105, 98, 40, 37, 100, 41, 32, 61, 32, 37, 108, 108, 100, 92, 110, 0
