; Generated by AC Compiler v1.0.0 — target: x86_64-linux-gnu
; Assemble: nasm -felf64 output.asm
; Link:     gcc output.o runtime.o -o program

section .text


global main
main:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    ; [call]
    lea rdi, [rel .Lstr_0x602ce39a1d98]
    xor eax, eax
    call printf
    mov qword [rbp-8], rax
    ; [ret]
    mov rax, 0
    leave
    ret
.L1:
    ; [ret]
    leave
    ret
    ; implicit void return
    leave
    ret


section .data

.Lstr_0x602ce39a1d98:
    db 72, 101, 108, 108, 111, 44, 32, 87, 111, 114, 108, 100, 33, 92, 110, 0
.Lstr_0x602ce39a1d98:
    db 72, 101, 108, 108, 111, 44, 32, 87, 111, 114, 108, 100, 33, 92, 110, 0
